version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    depends_on:
      - mongo

  socket-server:
    build: .
    command: python socket_server.py
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
